// Translations for the phrases
const translations = {
    en: {
        heading: "Welcome to Our Website",
        paragraph: "This is a sample paragraph to demonstrate language selection on a webpage. Choose a language from the dropdown above to see the content change.",
        heading_2: "Destinations",
        headings_1: "This has a very stunning wildlife safaris ",
        headings_2: "This is a breathtaking place for natural wonders ",
        headings_3: "Where diverse landscapes meet vibrant cities. ",
        headings_4: "Where history meets modernity. ",
        headings_5: "Where ancient meets modern ",
        headings_6: "Where stunning coasts meet vibrant cities.",
        headings_7: "Where icy expanses meet endless adventure.",
        heading_4: "See more",
        heading_4: "See more",
        heading_4: "See more",
        heading_4: "See more",
        heading_4: "See more",
        heading_4: "See more",
        heading_4: "See more",
        heading_5: "Asia",
        heading_6: "Europe",
        heading_7: "North America",
        heading_8: "South America",
        heading_9: "Africa",
        heading_10: "Antarctica",
        heading_11:"Austrailia",
        paragraph_2: "This is my review about this company",
        paragraph_4: "A truly exceptional service. The team was knowledgeable and responsive. Highly recommended!",
        paragraph_5: "Professional, reliable, and always willing to go the extra mile. I couldn't be happier with my experience.",
        paragraph_6: "Contact us",
        paragraph_7: "About",
        paragraph_8: "Privacy and Cookies Statement",
        paragraph_9: "Terms of Use",
        paragraph_10: "Terms And Conditions",
        paragraph_11: "Copyright 2024 Travel Website | All rights reserved."
    },

    fr: {
        heading: "Bienvenue sur notre site Web",
        paragraph: "Ceci est un paragraphe d'exemple pour démontrer la sélection de la langue sur une page Web. Choisissez une langue dans le menu déroulant ci-dessus pour voir le contenu changer.",
        heading_2: "Destinations",
        headings_1: "Cela offre des safaris animaliers très impressionnants.",
        headings_2: "C'est un endroit à couper le souffle pour les merveilles naturelles. ",
        headings_3: "Là où des paysages diversifiés rencontrent des villes vibrantes.",
        headings_4: "Où l'histoire rencontre la modernité. ",
        headings_5: "Où l'ancien rencontre le moderne. ",
        headings_6: "Là où les côtes époustouflantes rencontrent des villes dynamiques.",
        headings_7: "Là où les étendues glacées rencontrent l'aventure sans fin. ",
        heading_4: "Voir plus",
        heading_4: "Voir plus",
        heading_4: "Voir plus",
        heading_4: "Voir plus",
        heading_4: "Voir plus",
        heading_4: "Voir plus",
        heading_4: "Voir plus",
        heading_5: "Asie",
        heading_6: "Europe",
        heading_7: "Amérique du Nord",
        heading_8: "Amérique du Sud",
        heading_9: "Afrique",
        heading_10: "Antarctique",
        heading_11: "Australie",
        paragraph_2: "Voici mon avis sur cette entreprise",
        paragraph_4: "Un service exceptionnellement excellent. L'équipe était compétente et réactive. Hautement recommandé !",
        paragraph_5: "Professionnel, fiable et toujours prêt à faire le surplus. Je ne pourrais pas être plus heureux avec mon expérience.",
        paragraph_6: "Nous contacter",
        paragraph_7: "À propos",
        paragraph_8: "Déclaration de confidentialité et de cookies",
        paragraph_9: "Conditions d'utilisation",
        paragraph_10: "Conditions générales",
        paragraph_11: "Tous droits réservés. Copyright 2024 Site web de voyage."
    },

    es: {
        heading: "Bienvenido a nuestro sitio web",
        paragraph: "Este es un párrafo de ejemplo para demostrar la selección de idioma en una página web. Elija un idioma en el menú desplegable de arriba para ver el cambio de contenido.",
        heading_2: "Destinos",
        headings_1: "Das bietet sehr beeindruckende Wildtiersafaris.",
        headings_2: "Este es un lugar impresionante para las maravillas naturales. ",
        headings_3: "Donde paisajes diversos se encuentran con ciudades vibrantes.",
        headings_4: "Donde la historia se encuentra con la modernidad. ",
        headings_5: "Donde lo antiguo se encuentra con lo moderno.",
        headings_6: "Donde las costas impresionantes se encuentran con ciudades vibrantes. ",
        headings_7: "Donde las extensiones de hielo se encuentran con la aventura infinita. ",
        heading_4: "Ver más",
        heading_4: "Ver más",
        heading_4: "Ver más",
        heading_4: "Ver más",
        heading_4: "Ver más",
        heading_4: "Ver más",
        heading_4: "Ver más",
        heading_5: "Asia",
        heading_6: "Europa",
        heading_7: "América del Norte",
        heading_8: "América del Sur",
        heading_9: "África",
        heading_10: "Antártida",
        heading_11:"Australia",
        paragraph_2: "Esta es mi reseña sobre esta empresa",
        paragraph_4: "Un servicio verdaderamente excepcional. El equipo fue conocedor y receptivo. ¡Muy recomendado!",
        paragraph_5: "Profesional, confiable y siempre dispuesto a ir más allá. No podría estar más feliz con mi experiencia.",
        paragraph_6: "Contáctenos",
        paragraph_7: "Acerca de",
        paragraph_8: "Declaración de privacidad y cookies",
        paragraph_9: "Términos de uso",
        paragraph_10: "Términos y condiciones",
        paragraph_11: "Todos los derechos reservados. Copyright 2024 Sitio web de viajes."
    },

    de: {
        heading: "Willkommen auf unserer Website",
        paragraph: "Dies ist ein Beispielabsatz zur Demonstration der Sprachauswahl auf einer Webseite. Wählen Sie eine Sprache aus dem Dropdown-Menü oben, um den Inhalt zu ändern.",
        heading_2: "Ziele",
        headings_1: "Esto ofrece safaris de vida silvestre muy impresionantes.",
        headings_2: "Dies ist ein atemberaubender Ort für Naturwunder. ",
        headings_3: "Wo vielfältige Landschaften auf lebendige Städte treffen. ",
        headings_4: "Wo Geschichte auf Moderne trifft. ",
        headings_5: "Wo Alt auf Neu trifft. ",
        headings_6: "Wo atemberaubende Küsten auf lebendige Städte treffen.",
        headings_7: "Wo eisige Weiten auf endlose Abenteuer treffen.",
        heading_4: "Mehr sehen",
        heading_4: "Mehr sehen",
        heading_4: "Mehr sehen",
        heading_4: "Mehr sehen",
        heading_4: "Mehr sehen",
        heading_4: "Mehr sehen",
        heading_4: "Mehr sehen",
        heading_5: "Asien",
        heading_6: "Europa",
        heading_7: "Nordamerika",
        heading_8: "Südamerika",
        heading_9: "Afrika",
        heading_10: "Antarktis",
        heading_11:"Australien",
        paragraph_2: "Das ist meine Bewertung über dieses Unternehmen",
        paragraph_4: "Ein wirklich außergewöhnlicher Service. Das Team war kompetent und reaktionsschnell. Sehr empfehlenswert!",
        paragraph_5: "Professionell, zuverlässig und immer bereit, den extra Schritt zu gehen. Ich könnte nicht glücklicher mit meiner Erfahrung sein.",
        paragraph_6: "Kontaktieren Sie uns",
        paragraph_7: "Über uns",
        paragraph_8: "Datenschutzerklärung und Cookie-Richtlinie",
        paragraph_9: "Nutzungsbedingungen",
        paragraph_10: "Allgemeine Geschäftsbedingungen",
        paragraph_11: "Alle Rechte vorbehalten. Copyright 2024 Reise-Website."
    }
};

// Function to change language dynamically
function changeLanguage() {
    const selectedLanguage = document.getElementById('language').value;
    const elements = Object.keys(translations[selectedLanguage]);

    elements.forEach(id => {
        const element = document.getElementById(id);
        if (element) {
            element.innerText = translations[selectedLanguage][id];
        }
    });
}
